// Responsibility: synthetic behavior/persistence regression tests. Tests ClipNestCore only.
// Development status: complete.
import XCTest
@testable import ClipNestCore
final class ClipboardStoreTests: XCTestCase {
    var root: URL!
    override func setUp() { root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString) }
    override func tearDown() { try? FileManager.default.removeItem(at: root) }
    func makeStore() -> ClipboardStore { ClipboardStore(file: root.appendingPathComponent("pins.json")) }
    func testRecentBoundAndDeduplication() {
        let store = makeStore()
        for text in ["A", "B", "C", "D", "B"] { store.ingest(text) }
        XCTAssertEqual(store.recent.map(\.text), ["B", "D", "C"])
        store.ingest(" \n "); store.ingest(String(repeating: "x", count: 1_048_577))
        XCTAssertEqual(store.recent.count, 3)
    }
    func testUnlimitedPinsAndRestartOnlyPersistsPins() throws {
        let store = makeStore()
        for index in 0..<8 { store.ingest("Synthetic \(index)"); XCTAssertTrue(store.pin(store.recent[0].id)) }
        XCTAssertEqual(store.pinned.count, 8); XCTAssertEqual(store.recent.count, 3)
        XCTAssertFalse(store.pin(store.recent[0].id))
        let loaded = makeStore()
        XCTAssertEqual(loaded.pinned, store.pinned); XCTAssertTrue(loaded.recent.isEmpty)
        let permissions = try FileManager.default.attributesOfItem(atPath: root.appendingPathComponent("pins.json").path)[.posixPermissions] as? NSNumber
        XCTAssertEqual(permissions?.intValue, 0o600)
    }
    func testDeleteUndoPreservesOrder() {
        let store = makeStore()
        for text in ["A", "B", "C"] { store.ingest(text); _ = store.pin(store.recent[0].id) }
        XCTAssertTrue(store.delete(store.pinned[1].id)); XCTAssertEqual(makeStore().pinned.map(\.text), ["A", "C"])
        store.undoDelete(); XCTAssertEqual(makeStore().pinned.map(\.text), ["A", "B", "C"])
    }
    func testCorruptFileIsPreserved() throws {
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        let file = root.appendingPathComponent("pins.json"), original = Data("invalid synthetic JSON".utf8)
        try original.write(to: file)
        let store = makeStore(); XCTAssertNotNil(store.error)
        store.ingest("A"); XCTAssertFalse(store.pin(store.recent[0].id))
        XCTAssertEqual(try Data(contentsOf: file), original)
    }
    func testFailedPersistenceRollsBack() throws {
        try Data().write(to: root)
        let store = makeStore(); store.ingest("A")
        XCTAssertFalse(store.pin(store.recent[0].id)); XCTAssertTrue(store.pinned.isEmpty)
    }
    func testPrivacyTypes() {
        for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.vendor.password", "com.vendor.private", "com.agilebits.onepassword", "com.apple.is-remote-clipboard"] { XCTAssertTrue(ClipboardPolicy.isSensitive(["public.utf8-plain-text", type])) }
        XCTAssertFalse(ClipboardPolicy.isSensitive(["public.utf8-plain-text", "public.rtf"]))
    }
}
