// Responsibility: synthetic behavior/persistence regression tests. Tests ClipNestCore only.
// Development status: complete.
import XCTest
import CoreGraphics
@testable import ClipNestCore
final class ClipboardStoreTests: XCTestCase {
    var root: URL!
    override func setUp() { root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString) }
    override func tearDown() { try? FileManager.default.removeItem(at: root) }
    func makeStore() -> ClipboardStore { ClipboardStore(file: root.appendingPathComponent("pins.json")) }
    func testRecentBoundAndDeduplication() {
        let store = makeStore()
        for text in ["A", "B", "C", "D", "B"] { store.ingest(text) }
        XCTAssertEqual(store.recent.map(\.text), ["B", "D", "C"])
        store.ingest(" \n "); store.ingest(String(repeating: "x", count: 1_048_577))
        XCTAssertEqual(store.recent.count, 3)
    }
    func testUnlimitedPinsAndRestartOnlyPersistsPins() throws {
        let store = makeStore()
        for index in 0..<8 { store.ingest("Synthetic \(index)"); XCTAssertTrue(store.pin(store.recent[0].id)) }
        XCTAssertEqual(store.pinned.count, 8); XCTAssertEqual(store.recent.count, 3)
        XCTAssertFalse(store.pin(store.recent[0].id))
        let loaded = makeStore()
        XCTAssertEqual(loaded.pinned, store.pinned); XCTAssertTrue(loaded.recent.isEmpty)
        let permissions = try FileManager.default.attributesOfItem(atPath: root.appendingPathComponent("pins.json").path)[.posixPermissions] as? NSNumber
        XCTAssertEqual(permissions?.intValue, 0o600)
    }
    func testDeleteUndoPreservesOrder() {
        let store = makeStore()
        for text in ["A", "B", "C"] { store.ingest(text); _ = store.pin(store.recent[0].id) }
        XCTAssertTrue(store.delete(store.pinned[1].id)); XCTAssertEqual(makeStore().pinned.map(\.text), ["A", "C"])
        store.undoDelete(); XCTAssertEqual(makeStore().pinned.map(\.text), ["A", "B", "C"])
    }
    func testCorruptFileIsPreserved() throws {
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        let file = root.appendingPathComponent("pins.json"), original = Data("invalid synthetic JSON".utf8)
        try original.write(to: file)
        let store = makeStore(); XCTAssertNotNil(store.error)
        store.ingest("A"); XCTAssertFalse(store.pin(store.recent[0].id))
        XCTAssertEqual(try Data(contentsOf: file), original)
    }
    func testFailedPersistenceRollsBack() throws {
        try Data().write(to: root)
        let store = makeStore(); store.ingest("A")
        XCTAssertFalse(store.pin(store.recent[0].id)); XCTAssertTrue(store.pinned.isEmpty)
    }
    func testPrivacyTypes() {
        for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.vendor.password", "com.vendor.private", "com.agilebits.onepassword", "com.apple.is-remote-clipboard"] { XCTAssertTrue(ClipboardPolicy.isSensitive(["public.utf8-plain-text", type])) }
        XCTAssertFalse(ClipboardPolicy.isSensitive(["public.utf8-plain-text", "public.rtf"]))
    }
    func testUsageRankingPersistenceAndStableTies() {
        let store = makeStore()
        for text in ["A", "B", "C"] { store.ingest(text); _ = store.pin(store.recent[0].id) }
        let a = store.pinned[0].id, b = store.pinned[1].id, c = store.pinned[2].id
        XCTAssertTrue(store.recordCopy(c)); XCTAssertTrue(store.recordCopy(b))
        XCTAssertEqual(store.sortedPins.map(\.text), ["B", "C", "A"])
        XCTAssertTrue(store.recordCopy(c))
        XCTAssertEqual(makeStore().sortedPins.map(\.text), ["C", "B", "A"])
        XCTAssertEqual(makeStore().sortedPins.map(\.copyCount), [2, 1, 0])
        XCTAssertEqual(store.pinned.map(\.id), [a, b, c]) // Storage order never shifts during interaction.
        XCTAssertTrue(store.delete(c)); store.undoDelete()
        XCTAssertEqual(makeStore().sortedPins.first?.copyCount, 2)
    }
    func testLegacyPinsLoadWithoutRewritingAndCounterFailureRollsBack() throws {
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        let file = root.appendingPathComponent("pins.json")
        let legacy = Data("[{\"id\":\"00000000-0000-0000-0000-000000000001\",\"text\":\"Synthetic legacy\"}]".utf8)
        try legacy.write(to: file)
        let store = makeStore()
        XCTAssertNil(store.error); XCTAssertEqual(store.pinned[0].copyCount, 0)
        XCTAssertEqual(try Data(contentsOf: file), legacy)
        XCTAssertTrue(store.recordCopy(store.pinned[0].id)); XCTAssertEqual(makeStore().pinned[0].copyCount, 1)
        try FileManager.default.removeItem(at: root)
        try Data().write(to: root)
        XCTAssertFalse(store.recordCopy(store.pinned[0].id)); XCTAssertEqual(store.pinned[0].copyCount, 1)
    }

    func testNearbyTrashTargetStaysInsidePanelAtEdgesAndScrolledRows() {
        let bounds = CGRect(x: 0, y: 0, width: 380, height: 698)
        for point in [CGPoint(x: 30, y: 640), CGPoint(x: 340, y: 640), CGPoint(x: 30, y: 250), CGPoint(x: 340, y: 250)] {
            let source = CGRect(x: 20, y: point.y - 18, width: 340, height: 36)
            let target = DragTargetGeometry.target(origin: point, source: source, bounds: bounds)
            XCTAssertTrue(bounds.contains(target)); XCTAssertFalse(target.contains(point))
            XCTAssertLessThan(hypot(target.midX - point.x, target.midY - point.y), 100)
            XCTAssertEqual(target, DragTargetGeometry.target(origin: point, source: source, bounds: bounds))
        }
        let partlyScrolled = CGRect(x: 20, y: -12, width: 340, height: 36)
        XCTAssertTrue(bounds.contains(DragTargetGeometry.target(origin: CGPoint(x: 350, y: 5), source: partlyScrolled, bounds: bounds)))
    }

}
