// Responsibility: bounded recent text and atomic pinned persistence. Used by ClipboardMonitor/UI.
// Development status: complete.
import Foundation

public struct Snippet: Codable, Equatable, Identifiable {
    public let id: UUID
    public let text: String
    public private(set) var copyCount: UInt64
    public init(text: String) { id = UUID(); self.text = text; copyCount = 0 }
    private enum CodingKeys: String, CodingKey { case id, text, copyCount }
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(UUID.self, forKey: .id)
        text = try values.decode(String.self, forKey: .text)
        copyCount = try values.decodeIfPresent(UInt64.self, forKey: .copyCount) ?? 0
    }
    fileprivate mutating func recordCopy() { if copyCount < UInt64.max { copyCount += 1 } }
}

public enum ClipboardPolicy {
    // Conventional producer markers, including password-manager private payloads.
    public static func isSensitive(_ types: [String]) -> Bool {
        types.contains { type in
            let value = type.lowercased()
            return value == "org.nspasteboard.concealedtype" || value == "org.nspasteboard.transienttype"
                || value == "org.nspasteboard.autogeneratedtype" || value == "com.apple.is-remote-clipboard"
                || value.contains("password") || value.contains("concealed") || value.contains("transient")
                || value.contains("private") || value.contains("1password") || value.contains("keepass")
        }
    }
    public static func accepts(_ text: String) -> Bool {
        !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && text.utf8.count <= 1_048_576
    }
}

public final class ClipboardStore {
    public private(set) var recent: [Snippet] = []
    public private(set) var pinned: [Snippet] = []
    public private(set) var error: String?
    private let file: URL
    private var lastDeleted: (Int, Snippet)?
    public var canUndo: Bool { lastDeleted != nil }
    // Usage descending; equal counts retain original pin order, across launches.
    public var sortedPins: [Snippet] {
        pinned.enumerated().sorted {
            $0.element.copyCount == $1.element.copyCount ? $0.offset < $1.offset : $0.element.copyCount > $1.element.copyCount
        }.map(\.element)
    }
    // Only call after NSPasteboard confirms a successful write. No reordering during interaction.
    @discardableResult public func recordCopy(_ id: UUID) -> Bool {
        guard let index = pinned.firstIndex(where: { $0.id == id }) else { return false }
        let old = pinned; pinned[index].recordCopy()
        return persist(orRestore: old)
    }
    public init(file: URL) {
        self.file = file
        guard FileManager.default.fileExists(atPath: file.path) else { return }
        do {
            let records = try JSONDecoder().decode([Snippet].self, from: Data(contentsOf: file))
            var seen = Set<String>()
            pinned = records.filter { ClipboardPolicy.accepts($0.text) && seen.insert($0.text).inserted }
        } catch { self.error = "Could not load pinned snippets. Existing file was preserved." }
    }
    public func ingest(_ text: String) {
        guard ClipboardPolicy.accepts(text) else { return }
        recent.removeAll { $0.text == text }
        recent.insert(Snippet(text: text), at: 0)
        recent = Array(recent.prefix(3))
    }
    @discardableResult public func pin(_ id: UUID) -> Bool {
        guard let item = recent.first(where: { $0.id == id }), !pinned.contains(where: { $0.text == item.text }) else { return false }
        let old = pinned
        pinned.append(item)
        return persist(orRestore: old)
    }
    @discardableResult public func delete(_ id: UUID) -> Bool {
        guard let index = pinned.firstIndex(where: { $0.id == id }) else { return false }
        let old = pinned, item = pinned.remove(at: index)
        guard persist(orRestore: old) else { return false }
        lastDeleted = (index, item)
        return true
    }
    public func undoDelete() {
        guard let (index, item) = lastDeleted, !pinned.contains(where: { $0.text == item.text }) else { return }
        let old = pinned
        pinned.insert(item, at: min(index, pinned.count))
        if persist(orRestore: old) { lastDeleted = nil }
    }
    private func persist(orRestore old: [Snippet]) -> Bool {
        // A corrupt file is never overwritten implicitly: preserve it for recovery.
        guard error == nil else { pinned = old; return false }
        do {
            let parent = file.deletingLastPathComponent()
            try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
            try JSONEncoder().encode(pinned).write(to: file, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: file.path)
            return true
        } catch {
            pinned = old
            // Transient save errors are retryable; load corruption remains locked.
            return false
        }
    }
}
